### ISSUE TITLE
issues :(

### ISSUE THREAD

**Issue by mr007guy** [ORCA666/Cobalt-Wipe#3]
connection refused

**Comment by mr007guy** [comment]
connection refused :(

**Comment by ORCA666** [comment]
@mr007guy can u upload a screenshot or the exact error message ?

**Comment by mr007guy** [comment]
Hi thank you for replying back, at first nothing worked but i noticed i had
to extract the cobaltstrike.7z folder which should be added to the
instruction incase others have issues. Heres the error message :)
[!] Trapped java.net.ConnectException during client connect [ dialog
action: connect]: Connection refused (Connection refused)
